// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

// Filters
export const AUCTION_FILTERS_ALL = "AUCTION_FILTERS_ALL"
export const AUCTION_FILTERS_FOR_SALE = "AUCTION_FILTERS_FOR_SALE"
export const AUCTION_FILTERS_NOT_FOR_SALE = "AUCTION_FILTERS_NOT_FOR_SALE"
export const PUTCALL_FILTERS_ALL = "PUTCALL_FILTERS_ALL"
export const PUTCALL_FILTERS_PUT = "PUTCALL_FILTERS_PUT"
export const PUTCALL_FILTERS_CALL = "PUTCALL_FILTERS_CALL"
export const EXPIRY_FILTERS_ALL = "EXPIRY_FILTERS_ALL"
export const EXPIRY_FILTERS_EXPIRED = "EXPIRY_FILTERS_EXPIRED"
export const EXPIRY_FILTERS_NOT_EXPIRED = "EXPIRY_FILTERS_NOT_EXPIRED"
export const STYLES_FILTERS_ALL = "STYLES_FILTERS_ALL"
export const STYLES_FILTERS_AMERICAN = "STYLES_FILTERS_AMERICAN"
export const STYLES_FILTERS_EUROPEAN = "STYLES_FILTERS_EUROPEAN"

// Block
export const CURRENT_BLOCK = "CURRENT_BLOCK"

// Token Mapping
export const TOKEN_DATA = "TOKEN_DATA"
